ghtk:
  api_token: 947Dde88E641E9989C353cCD02E6FDa1A547b53a
  url_service: https://dev.giaohangtietkiem.vn/

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useUnicode=yes&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}