ghtk:
  api_token: 947Dde88E641E9989C353cCD02E6FDa1A547b53a
  url_service: https://dev.giaohangtietkiem.vn/

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://dalafarm-db.crvptvmickvz.ap-southeast-1.rds.amazonaws.com:3306/ghn?useUnicode=yes&characterEncoding=UTF-8
    username: dalafarm
    password: d4l4f4rm
