spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dlf?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: dalafarm
  jackson:
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true

dalafarm:
  name: DalaFarm
  districtId: 772
  address: 317 Lô D, chung cư Lạc Long Quân, đường Tống Văn Trân
  tel: 0941336174 - 0906951498
